version: "3.8"

services:
  app:
    image: spring-boot-app-image:latest
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        MAVEN_IMAGE: docker.io/library/maven:3.9-eclipse-temurin-21
        JRE_IMAGE: docker.io/library/eclipse-temurin:21-jre
    ports:
      - "80:80"